### ISSUE TITLE
Change device type

### ISSUE THREAD

**Issue by n0tkazz** [kopiro/homebridge-playstation#1]
Hello !

I was trying to add my PS5 to HomeKit, i found the playactor guide and then your plugin. Great work !
Is it possible to change the device type of the switch created by the plugin ?

For example, with https://github.com/unknownskl/homebridge-smartglass, the Xbox shows as a "set-top-box" with a nice icon in Homebridge
<img width="116" alt="Capture d’écran 2022-02-08 à 18 27 05" src="https://user-images.githubusercontent.com/94456260/153042183-db892b91-8e81-423a-a43c-f05c34705e9a.png">

Thx !

**Comment by kopiro** [comment]
Done! 

You can find the new category in version `1.1.0`

**Comment by adamrzanek** [comment]
I think Device type should be an option. I prefer it as a switch - you can make automations easier with it

**Comment by kopiro** [comment]
Hey, I'm interested in knowing what you can do more with a switch instead of a TV service?

**Comment by adamrzanek** [comment]
TV service isn’t available in 3rd party homekit apps. So it cannot be used in conditions. I was using PS5 with cmdswitch to trigger different modes of my hue sync box. :) In theory i like Tv service mode of course :) Otherwise i looooove your plugin - keep going great job :D
