### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HellJohny** [kopiro/homebridge-playstation#10]
Hi, 
can you help me with this problem ? Everytime i press the button in home app in HB log writes "[playstation] Unable to request credentials" and nothing happens. I have latest version o you plugin. Thanks for reply :)

**Comment by kopiro** [comment]
Hey, have you followed the guide to configure the playstation before first use?

**Comment by HellJohny** [comment]
Yes man

**Comment by HellJohny** [comment]
Can i reset the configure and start again

**Comment by kopiro** [comment]
Hey, can you check if the file `/home/homebridge/.config/playactor/credentials.json` exists?

**Comment by HellJohny** [comment]
Sorry. How can i find it ?

**Comment by kopiro** [comment]
Go to Homebridge terminal, and type this: `ls -la /home/homebridge/.config/playactor/credentials.json`
