### ISSUE TITLE
Assessory not appearing after registering the app with playstation . 

### ISSUE THREAD

**Issue by billbazza** [kopiro/homebridge-playstation#102]
After registering the app with Playstation and enabling remote support, I am asked to add the device manually in the Home app but no app accessory appears. 

I've removed all config, including the mentioned folder in the docs and reinstalled everything but nothing seems to work. 

I recently upgraded node to v20.11.0. Could this be an issue?

[2/26/2024, 2:50:59 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 81C9) is running on port 52611. [2/26/2024, 2:50:59 PM] PS5-772 E3B9 is running on port 39661. 
[2/26/2024, 2:50:59 PM] Please add [PS5-772 E3B9] manually in Home app. Setup Code: XXXXXXXX

OS | Ubuntu Jammy Jellyfish (22.04.2 LTS)
-- | --
192.168.4.60
pi4
root
v20.11.0
/opt/homebridge/bin
/var/lib/homebridge
/var/lib/homebridge/config.json
/var/lib/homebridge/node_modules
GMT+0000
Yes

**Comment by brycebolton17** [comment]
same problem here! Did you found a solution? It is worked correctly on mac, but i get this error on my raspberry pi.
