### ISSUE TITLE
Accessory Doesn't Appear When Trying to Add

### ISSUE THREAD

**Issue by chrisdudek** [kopiro/homebridge-playstation#11]
**Describe Your Problem:**
I installed the previous version of this Plugin. When I was receiving connection errors as noted in a previous issue, I removed the plugin from Homebridge. I also remove the Bridge and Accessory from my Home app. With you latest update, I have now reinstalled the Plugin. I can get the Bridge added to the Home app, but the PS accessory does not show up in the list of available devices.

**Logs:**

Discovered device: {
  address: { address: '192.168.1.8', family: 'IPv4', port: XXXX, size: 170 },
  hostRequestPort: 997,
  extras: {
    statusLine: '620 Server Standby',
    statusCode: '620',
    statusMessage: 'Server',
    status: 'STANDBY'
  },
  discoveryVersion: '00030010',
  systemVersion: '09090001',
  id: 'XXXXXXXXXX,
  name: 'PS5-XXX',
  status: 'STANDBY',
  type: 'PS5'
}
[2/10/2022, 3:49:59 PM] PS5-XXX XXXE is running on port XXXXX.
[2/10/2022, 3:49:59 PM] Please add [PS5-XXX XXXE] manually in Home app. Setup Code: XXX-XX-XXX

**Plugin Config:**

        {
            "pollInterval": 5000,
            "platform": "playstation",
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": XXXXX
            }

**NOTE - the Port in the Config != the Port in my Homebridge Logs. Not sure if they are meant to match.

**Environment:**

* **Plugin Version**: homebridge-playstation [v1.2.2]
* **Homebridge Version**: [v1.4.0]
* **Node.js Version**: [v16.13.2]
* **NPM Version**: [v8.1.2]
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by kopiro** [comment]
Hey, can try to manually reset the cache and remove this accessory?

**Comment by chrisdudek** [comment]
I was able to get it to work. After trying everything, I went into the Homebridge Terminal and removed all of the files in the Accessories and the Persist directories. Then I restarted Homebridge. After that, I was able to add the PS5 back into the Home app.

Now, I would probably recommend figuring out which files in each directory you need to remove rather than remove them all. I had to re-add all of my Homebridge accessories to HomeKit / Home app since they all showed as not responding. Luckily that was about 5-10 min of work to get back to where I was. But for others that don't want to go through that, try to find the files you need to remove and just delete those. Keep the ones of your existing accessories/bridges that are working.
