### ISSUE TITLE
Please add [PS5 XYZ] manually in Home app. Setup Code: 111-22-333

### ISSUE THREAD

**Issue by DavidLinhares-DV** [kopiro/homebridge-playstation#115]
Missing the message "Please add [PS5 XYZ] manually in Home app. Setup Code: 111-22-333"

I have been able to follow all of your instructions without issue, but i'am not seing the final message **Please add [PS5 XYZ] manually in Home app. Setup Code: 111-22-333** after restarting homebridge.

Could you help me find the setup-code ? 

**Environment:**

* **Plugin Version**: 1.6.2
* **Homebridge Version**: 1.8.4
* **Node.js Version**: v20.17.0
* **NPM Version**: 10.8.2
* **Operating System**: Ubuntu server

**Comment by ghosh** [comment]
Seems like the device id is not getting saved automatically. See #101.

Here is how I solved this:- 

#### 1. After running `homebridge-playstation-login` and authenticating and linking the device you should be seeing an output like this below. Copy the device id from the response.

<img width="738" alt="ps-login" src="https://github.com/user-attachments/assets/8c9a3ee3-b6dd-4b14-bf5f-3634176b6d61">

#### 2. Then go to the playstation plugin config and add the number to the override section

<img width="797" alt="ps-override" src="https://github.com/user-attachments/assets/f2bf08b7-8305-4115-b0cd-628f324b6ead">

#### 3. Restart homebridge

The connection id should show up now.

**Comment by DavidLinhares-DV** [comment]
Worked perfectly thank you for your help !!!
