### ISSUE TITLE
Turning off ps5 crashes hb

### ISSUE THREAD

**Issue by adamrzanek** [kopiro/homebridge-playstation#13]
Plugin crashes homebridge instanace when I’m putting PlayStation to sleep.

![7FA38345-D139-4742-A29C-4984A8677454](https://user-images.githubusercontent.com/65444919/154548087-039cfb16-ce7d-479b-b510-fd392792206b.png)

**Comment by adamrzanek** [comment]
It’s only happening when I’m sleep ps5 from the console menu. It’s all good from the home app

**Comment by fate8383** [comment]
![image](https://user-images.githubusercontent.com/17381874/154772012-c9b188df-3c21-4b7f-938c-a04805542793.jpeg)

Similar problem, but I also was not able to sleep PS5 from home app, as for errors shows then put it on sleep from remote and it crashed HB.

**Comment by kopiro** [comment]
@dhleong this is the issue I mentioned you; is there a way to make sure this error doesn't throw to the main thread?

**Comment by kopiro** [comment]
Have you installed latest version of the plugin?

**Comment by fate8383** [comment]
I am on the latest version. I had to disable the plugin as it breaks HB every time I put it to sleep via console.

**Comment by adamrzanek** [comment]
It’s have exactly the same problem

**Comment by fate8383** [comment]
Is it just two of us having this problem? I feel like this bug is almost makes the plugin unusable for everyone but I am not sure. Something with device or account specific issue causing this?

**Comment by adamrzanek** [comment]
Next week I will try to login again to my ps remote. Maybe it’s something with early version of the plugin and updating it to latest version

**Comment by fate8383** [comment]
I am a new user since latest version, never had any update to this plugin, I can remove and add again maybe. But a little hint like what is causing this? So maybe I can modify from my side.

**Comment by adamrzanek** [comment]
Don’t know. I was using playactor before without the plugin before and it wasn’t happening then. I can’t check right now because I am 2500km from home 😂

>

**Comment by kopiro** [comment]
Hello; please try out the [new version ](https://github.com/kopiro/homebridge-playstation/releases/tag/v1.3.1) and let me know

**Comment by fate8383** [comment]
Ok it didn't crash the HB with the latest update. I am still getting this 403 registration error, you can see in my previous log screenshot. What is that? Should I worry about?
