### ISSUE TITLE
Siri is confused :)

### ISSUE THREAD

**Issue by adamrzanek** [kopiro/homebridge-playstation#14]
https://github.com/kopiro/homebridge-playstation/issues/1#issuecomment-1033099339 one thing I’ve noticed. When I’m saying “hey Siri, turn on the tv” PlayStation is also turning on when the accessory type is set top box :(

**Comment by kopiro** [comment]
Yeah, I noticed this too! This is beacuse the PlayStation is setup as TV top box.

**Comment by adamrzanek** [comment]
Yup. That’s why I would love to have an option to change it to the switch service

**Comment by sterumbelow** [comment]
Isn't that because you've got the setting enabled under HDMI on the PlayStation? You can disable it turning on the TV when it's turned on!

**Comment by adamrzanek** [comment]
No it’s different. Siri is trying to turn all the tvs in the room. Same with hue box plugin but with this it is not bothered if me. I’ve made workaround for this - I’ve created shortcut with phrase “turn in the tv” and it’s working for now

>
