### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by adamjthompson** [kopiro/homebridge-playstation#15]
I am having trouble getting started with the plugin. I am on Windows 11, and when I run the **homebridge-playstation-login** command, I receive only the following error:

```
Unable to locate device: device (any)
```

My PS5 is powered on and is the only PlayStation device currently on my network. Any ideas? Thanks!

**Comment by kopiro** [comment]
Hello; this looks like a bug in the underyling playactor library: https://github.com/dhleong/playactor
Perhaps Windows is not uspported; Please open an issue on their side, thanks!
