### ISSUE TITLE
homebridge terminal user password?

### ISSUE THREAD

**Issue by DifferentComputers** [kopiro/homebridge-playstation#17]
**Describe Your Problem:**

when running the install command in the homebridge terminal window, a password is required, even though no password is set for the homebridge user.

:/var/lib/homebridge$ homebridge-playstation-login
No credentials for PSSystem and unable to request (need root permissions).
Attempting to request root permissions now (we will relinquish them as soon as possible)...
[sudo] password for homebridge:
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: elementary Loki (0.4.1 Loki)

**Comment by DifferentComputers** [comment]
OK, I managed to set a homebridge user password. but now:

homebridge@Loki:/var/lib/homebridge$ homebridge-playstation-login
No credentials for psSystem and unable to request (need root permissions).
Attempting to request root permissions now (we will relinquish them as soon as possible)...
[sudo] password for homebridge:           
Sorry, user homebridge is not allowed to execute '/usr/local/bin/node /usr/local/bin/homebridge-playstation-login --credentials /home/homebridge/.config/playactor/credentials.json --proxied-user-id 999' as root on Loki.

Can anyone assist?

**Comment by ijv182** [comment]
I’m having the same issue as this. 

Does playactor need to be installed separately or is it included when this plugin is installed?

**Comment by shindekokoro** [comment]
You will need to add those directories to homebridge user in _/etc/sudoers_ file

**Comment by aceilort** [comment]
I typed `su [my main user]` and continued with `homebridge-playstation-login`. It worked 🤷‍♂️
