### ISSUE TITLE
Never getting HomeKit Code

### ISSUE THREAD

**Issue by Don-Blay** [kopiro/homebridge-playstation#18]
**Describe Your Problem:**
I believe I have set up the plug-in correctly; setting up the RemotePlay and enterying the pin. The logs state that it can find my PS5, but it never gives the message about Playstation 5 being discovered, but never gives the message about adding it manually to HomeKit with the Setup Code.  I can go into Home App and see the Playstation as a device under "Add Excessory), but again I don't know the code.

**Logs:**

2/28/2022, 4:50:46 PMPlaystation BridgeLoaded plugin 'homebridge-playstation'
2/28/2022, 4:50:46 PMPlaystation BridgeLoading 1 platforms...
2/28/2022, 4:50:46 PMPlaystation BridgeBridge is running on port 51866.
2/28/2022, 4:50:46 PMPlaystation BridgeplaystationDiscovered device: {
  address: { address: '192.168.1.246', family: 'IPv4', port: 9302, size: 158 },
  hostRequestPort: 997,
  extras: {
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE'
  },
  discoveryVersion: '00030010',
  systemVersion: '09090001',
  id: '78C8XXXXXXXX',
  name: 'PS5-XXX',
  status: 'AWAKE',
  type: 'PS5'
}

**Plugin Config:**

{
    "platform": "playstation",
    "pollInterval": 5000
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.3.1
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**: 
* **Operating System**: Debian

**Comment by mesoblaste** [comment]
The code is the same that the one you use to add homebridge as a bridge in Apple home app, which is displayed on the status page on homebridge under the QR code
