### ISSUE TITLE
EACCES: permission denied when entering Link code

### ISSUE THREAD

**Issue by sterumbelow** [kopiro/homebridge-playstation#24]
Hello, 

I've just got my PS5 set up and would like to add it to Homebridge/Home. I've followed your install guide and I'm getting to the final step and typing in the link code, but I'm running into the error below:

`EACCES: permission denied`
`Did not authenticate to any consoles.`

I've tried multiple times but I'm still running into the same problem. I noticed above you said to run this as a user, not as root. Could that be something I'm doing wrong? I've never run into this issue before and I'm not even sure how to run this 'as a user', if I'm not already!

I've already got the PS5 into the Home app, but it doesn't turn on/off when clicked, with the log saying:

`Device PS5-981 must be awake for initial registration`

I assume that's because it's not fully linked for remote play. Remote play is enabled though.

Thanks for your help, 
Ste.

**Comment by sterumbelow** [comment]
I could see there was a node issue in the log (next to Playstation). That is now updated and the node issue has gone, but I'm still unable to use the link code to fully add the device.

Any help appreciated! :)

**Comment by sterumbelow** [comment]
Anyone?

**Comment by LeFumiste** [comment]
I have the same problem !!!
Nobody to help us PLEASE ???

**Comment by sterumbelow** [comment]
> I have the same problem !!!
> 
> Nobody to help us PLEASE ???

Very frustrating. I still haven't sorted it.

**Comment by csoprano** [comment]
Hello everybody,

I also have the same problem: when I enter the activation code I get the error "EACCES: permission denied".
How can this be solved?

Thank you

**Comment by SebbySullivan** [comment]
Same here, followed every step of the instructions and just got this message:
`EACCES: permission denied, mdir
'/ home /homebridge/.config/playactor'
Discovering next device...
Did not authenticate to any consoles.  `

**Comment by sterumbelow** [comment]
I have finally fixed the issue!

Here's what I did:

So, first thing to know is it doesn't work because you don't have permission for it to write to the config file. Weirdly, my Homebridge terminal said 'admin' was an unknown user, even though that's the username. 

If you type 'whoami' you'll see your username is actually 'pi'. 

With that in mind, you need to be sure the config file is owned by 'pi'. 

Type

ls -la/home/pi

On the config line, you'll likely see root root. We need to make that say pi.

Type

sudo chown -R pi /home/pi

Then type

sudo chown -R pi /home/pi/.config

If you check the permissions again using 'ls -la /home/pi' you'll see it has changed. 

Now authenticate your PS5 again and it'll work!

Head over to your Home app, add accessory and enter your code. Voila! Remember this only works for rest mode on/odd. If you fully turn it off, it won't work.
