### ISSUE TITLE
Cannot complete setup

### ISSUE THREAD

**Issue by jude-ham** [kopiro/homebridge-playstation#27]
Describe Your Problem:
I tried using the plugin and got the following errors after setup. I tried running the command 'homebridge-playstation-login' in the command prompt, but got the message shown in the screenshots. I tried installing the app on my phone, and my laptop but none could find this PlayActor being referenced. Then, after temporarily skipping this step, i used the homekit code to set it up in the app but then got the error codes described below.

Logs:

[30/03/2022, 21:11:12] [playstation] Discovered device: {
  address: { address: 'XXXXX', family: 'IPv4', port: XXXXX, size: 157 },
  hostRequestPort: 997,
  extras: {
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE'
  },
  discoveryVersion: '00020020',
  systemVersion: '09508011',
  id: '0CFE45EA5205',
  name: 'My PS4',
  status: 'AWAKE',
  type: 'PS4'
}
[30/03/2022, 21:11:12] My PS4 E57F is running on port 53696.
[30/03/2022, 21:11:12] Please add [My PS4 E57F] manually in Home app. Setup Code: 363-27-611
[30/03/2022, 21:12:03] [playstation] Unable to request credentials *This is when i tried to toggle the power of it in the Home app*
[30/03/2022, 21:12:52] [playstation] Unable to locate device: with id 0CFE45EA5205 

Plugin Config:

{
    "bridge": {
        "name": "Homebridge 7B8F",
        "username": "XXXXX",
        "port": XXXXX,
        "pin": "XXXXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": XXXXX,
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "XXXXX",
            "password": "XXXXX",
            "apiKey": "XXXXX",
            "offlineAsOff": true,
            "platform": "Govee"
        },
        {
            "addresses": [
                "XXXXX"
            ],
            "name": "Jude Hamilton",
            "email": "XXXXX",
            "password": "XXXXX",
            "platform": "HomebridgeTPLinkTapo"
        },
        {
            "pollInterval": 5000,
            "platform": "playstation"
        }
    ]
}

Screenshots:
![image](https://user-images.githubusercontent.com/85447756/160926055-7e86c292-4404-4055-8ab1-3f064b7a9a2f.png)

Environment:

Plugin Version: 1.4.1
Homebridge Version: 1.4.0
Node.js Version: 16.14.0
NPM Version: 8.3.1
Operating System: Windows 11 Home

**Comment by mesoblaste** [comment]
It seems your problem is similar to this one :

[https://github.com/kopiro/homebridge-playstation/issues/30](https://github.com/kopiro/homebridge-playstation/issues/30)

Hope that helps
