### ISSUE TITLE
No terminal in homebridge UI - Mac 

### ISSUE THREAD

**Issue by jat80** [kopiro/homebridge-playstation#38]
**Describe Your Problem:**
Not sure how to configure playactor as I don’t have terminal access in homebridge UI as it’s installed on a Mac.  How do I configure it in terminal app with homebridge user?   

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by kopiro** [comment]
You should have a terminal window in the homebridge UI - otherwise just do `su homebridge` in any terminal and it should switch to homebridge user.

**Comment by jat80** [comment]
> You should have a terminal window in the homebridge UI - otherwise just do `su homebridge` in any terminal and it should switch to homebridge user.

No terminal window in macOS Homebridge UI or a setting to enable it.

Tried su homebridge just says sorry after entering in my pw.

**Comment by kopiro** [comment]
Go to homebridge, on bottom right press the plus button, and add the Homebridge Terminal widget.


![image](https://user-images.githubusercontent.com/839700/176125947-63f36111-ad20-4f64-9913-ed287ed97897.png)
![image](https://user-images.githubusercontent.com/839700/176125987-c3e4850b-f04f-4dba-8d67-e117f51719b1.png)

**Comment by jat80** [comment]
> Go to homebridge, on bottom right press the plus button, and add the Homebridge Terminal widget.
> 
> ![image](https://user-images.githubusercontent.com/839700/176125947-63f36111-ad20-4f64-9913-ed287ed97897.png) ![image](https://user-images.githubusercontent.com/839700/176125987-c3e4850b-f04f-4dba-8d67-e117f51719b1.png)

I don't have that option on macOS:


<img width="1435" alt="homebridge SS" src="https://user-images.githubusercontent.com/23650727/176129087-53c726f8-125e-4fe9-9fa3-eb91927695db.png">

**Comment by kopiro** [comment]
Can you type in your terminal: `id homebridge` ?

**Comment by AmericanNoir** [comment]
You can you use the native MacOS Terminal found in your utilities folder. 
"Applications > Utilities > Terminal"
It took a lot of beating my head against the wall to figure that out, yet I still haven't figured out the proper install for the Playstation to work.

**Comment by Jason-G-78** [comment]
Hi,
I just discovered this [Homebridge Playstation plugin](https://github.com/kopiro/homebridge-playstation) and get exactly the same thing on my iMac running macOS Big Sur (11.6.8). On the latest Node.js (v16.17.0).
Thought it was something I was doing wrong but I don't understand what the issue is, other than perhaps something permission related:
EACCES: permission denied, mkdir '/Users/<myusername>/.config/playactor'
The note on page of the plugin states:
"Now you need to configure PlayActor and follow the authentication process provided by the library; to do so, open the terminal in the HomeBridge UI (make sure you don't run these commands as root, you need to run them as homebridge user!) "
As far as I'm aware '<myusername>' is my 'homebridge user'
Any help appreciated.
Cheers

**Comment by LazaroFilm** [comment]
I'm having the same issue. I get after having to use the ps4-waker trick:
```
Open the PS4 Second Screen app and attempt to connect to the device named:
  PlayActor
EACCES: permission denied, mkdir '/root/.config/playactor'
```

**Comment by fredthedorfman** [comment]
@Jason-G-78 Give that .config folder read write access for the user you’re logged in as.  I just installed this plugin and got it working once I did that.

**Comment by Jason-G-78** [comment]
> @Jason-G-78 Give that .config folder read write access for the user you’re logged in as. I just installed this plugin and got it working once I did that.

Thanks I was hoping that might do it but now I get the following after entering the Link Device PIN:

Registration error: 403: Forbidden: Other Error

Discovering next device...

Did not authenticate to any consoles.


Tried the process again and now get the following despite restarting Homebridge and the PS5:

Connection successful, wait a bit so we can safely close the connection...

Discovering next device...

Please restart Homebridge now!
