### ISSUE TITLE
Homebridge Log says Unable to Locate Device every two minutes

### ISSUE THREAD

**Issue by DaveM8686** [kopiro/homebridge-playstation#41]
**Describe The Bug:**
When the PS5 is in sleep mode, I get this error every two minutes in the Homebridge log:
[6/28/2022, 4:25:29 PM] [playstation] Unable to locate device: with id [xxxxxxx] (blanked out for security)

This seems to have started since the PS5 turned off at the power point while in sleep mode (unintentionally).

It is also stopping the PS5 from being able to be turned on by Homebridge.  I've tried removing and readding the plugin repeatedly with no luck.  I think I need to be able to fully start the authentication process over, but each time I try that it remembers it from last time and never asks for the pin.  How can I get this to forget the authentication so I can start over?

**To Reproduce:**
Unsure, but possibly shut down PS5 incorrectly?

**Expected behavior:**
This log to not appear

**Logs:**
[6/28/2022, 4:25:29 PM] [playstation] Unable to locate device: with id [xxxxxxx]

**Plugin Config:**

```json
{
            "pollInterval": 5000,
            "platform": "playstation"
        }
```

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.15.0
* **NPM Version**: ??
* **Operating System**: Docker on Synology NAS

**Comment by Bat-Maniac** [comment]
I think there is a bug with the poll interval. Since I've changed it to 15000 ms this warning is gone.


```
{
   "pollInterval": 15000,
   "platform": "playstation"
}
```
