### ISSUE TITLE
Discover PS5 device over the specified interface

### ISSUE THREAD

**Issue by ZhibinLiIntel** [kopiro/homebridge-playstation#43]
**Describe Your Problem:**

Similar with Homebridge issue [#1957](https://github.com/homebridge/homebridge/issues/1957), I have this setup with **TWO** network interface. `eth0` for WAN, IP `192.168.1.2` and `eth1` for LAN, IP `192.168.66.1`.

By default, Homebridge itself is working over the WAN interface which is usually **NOT** what we want so it provides a parameter `mDNS` (or the latest `bind` option) to speficy the interface that you want it to work on.

Unfortunately this plugin seems to have a similar issue that the discovery process (originally `playactor browse`) is working over the WAN interface and it does **NOT** work even I bind the Homebridge interface to the correct one (LAN in my case).

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xxx:xx:xx",
        "port": xxxxx,
        "pin": "xxx-xx-xxx",
        "advertiser": "avahi",
        "bind": [
            "br-lan"
        ]
    },
    "platforms": [
        {
            "pollInterval": 5000,
            "platform": "playstation"
        }
    ]
```

I wonder if it's possible providing such an option like what Homebridge does

**Comment by kopiro** [comment]
Very interesting issue, but as PlayActor doesn't provide anything like that I think you should file an issue to them first.
