### ISSUE TITLE
ps5 not showing up on homekit

### ISSUE THREAD

**Issue by angelkr** [kopiro/homebridge-playstation#48]
<>

**Describe Your Problem:**
<i'm installing the plugin fine, complete the authentication with homebridge-playstation-login through terminal, yet i dont get an authorization link. i restart homebridge, i see the plugin loading and get the "Please add [PS5 XYZ] manually in Home app. Setup Code: 111-22-333" message in logs, however try as i might, my homekit doesnt find my device.>

**Logs:**

```
[21/09/2022, 19:58:45] [playstation] Discovered device: {
  address: { address: '192.168.1.19', family: 'IPv4', port: 9302, size: 161 },
  hostRequestPort: 997,
  extras: {
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE'
  },
  discoveryVersion: '00030010',
  systemVersion: '06000042',
  id: '78C8817EDA2B',
  name: 'PS5 Loutsa',
  status: 'AWAKE',
  type: 'PS5'
}
[21/09/2022, 19:58:45] PS5 Loutsa AB78 is running on port 34031.
[21/09/2022, 19:58:45] Please add [PS5 Loutsa AB78] manually in Home app. Setup Code: 668-33-715
```

**Plugin Config:**

```json
 {
            "pollInterval": 5000,
            "platform": "playstation"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:1.4.2
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by pablo-go** [comment]
same problem here, through homebridge I can control the plugin, but there is no way to get the icon to appear in homekit

**Comment by jerk2k** [comment]
Yes same here. I can turn the PS on in the Homebridge UI. But there is no connection in the Home App.

**Comment by Vati80** [comment]
same here. I try it multiple times.

**Comment by csoprano** [comment]
Hi,

i also have the same problem, the ps5 device is visible and i can only control it from homebridge but there is no way to add it to homekit. anyone know how to fix?

**Comment by Hammycutter** [comment]
Hey I think I solved it ,

Log in to the Homebridge UI 

In the top right hand corner hit the 3 lines then hit the 3 dots 

then go to Homebridge settings 

under reset click the arrow next to unpair bridges cameras etc 

delete PlayStation 

now on home kit search for new accessory 

your PlayStation will be waiting

**Comment by jerk2k** [comment]
> Hey I think I solved it ,
> 
> Log in to the Homebridge UI
> 
> In the top right hand corner hit the 3 lines then hit the 3 dots
> 
> then go to Homebridge settings
> 
> under reset click the arrow next to unpair bridges cameras etc
> 
> delete PlayStation
> 
> now on home kit search for new accessory
> 
> your PlayStation will be waiting

Thank you,
that worked for me and my setup.

**Comment by Nickvulkers** [comment]
> Log in to the Homebridge UI
> 
> In the top right hand corner hit the 3 lines then hit the 3 dots
> 
> then go to Homebridge settings
> 
> under reset click the arrow next to unpair bridges cameras etc
> 
> delete PlayStation
> 
> now on home kit search for new accessory
> 
> your PlayStation will be waiting

This worked! @kopiro this might be nice to put in the README somewhere, I think a lot of people had their stuff reset with the HomeKit update.

**Comment by csoprano** [comment]
Hi,

but doing this reset does it delete the devices from homekit and any automations created?
thanks

**Comment by Hammycutter** [comment]
> Hi,
> 
> but doing this reset does it delete the devices from homekit and any automations created? thanks

Only the PlayStation, worse case is you add it back , it does not mess with the rest of your automations

**Comment by Nickvulkers** [comment]
It only removes the PlayStation from Homebridge, after then restarting Homebridge and opening the "Add Accessory -> More options..." in the Home app it will show up fresh, allowing you to add it to HomeKit.

For me it didn't mess with any of my automations, because they had already been altered during the 16.2 update, the PS was completely gone.

**Comment by sametguzeldev** [comment]
> Hey I think I solved it ,
> 
> Log in to the Homebridge UI
> 
> In the top right hand corner hit the 3 lines then hit the 3 dots
> 
> then go to Homebridge settings
> 
> under reset click the arrow next to unpair bridges cameras etc
> 
> delete PlayStation
> 
> now on home kit search for new accessory
> 
> your PlayStation will be waiting

This did not work for me. I delete the playstation from there, I restart homebridge and it comes back again itself :(
