### ISSUE TITLE
EVENTEMIITER MEMORY LEAK

### ISSUE THREAD

**Issue by kowmen** [kopiro/homebridge-playstation#49]
Hi im using HOOBS last Update. 
Im trying to figured out problem with this. 
I installed pluginm register ps and after reset i have this in log.
1. 10. 2022 22:37:49Playstation BridgePS5-423 BFE7 is running on port 35647.
1. 10. 2022 22:38:04Playstation BridgeERROR(node:1076) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
Can you help me please

**Comment by tech4life2015** [comment]
I am running this app on a Ubuntu VM and getting the same error also when using the app

(node:7902) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

I have tried a full wipe and reload and it does not fix the issue.
