### ISSUE TITLE
Multiple PlayStation ?

### ISSUE THREAD

**Issue by mesoblaste** [kopiro/homebridge-playstation#5]
Hello,
How can I add multiple PlayStation devices.
I have a PS4 and a PS5 on the same network.
Following the instructions, my PS4 gets added automatically but not the PS5.
For information I already use PS4 waker platform plugin for my PS4 and playactor with Cmdswitch2 plugin for my PS5... but I got some malfunction now and then so I hoped to get a plugin to control both smoothly.
Also, when i log into playactor it didn't send me to Sony web page for login but I think it is because my credentials are already saved because of previous configuration...

**Comment by mesoblaste** [comment]
I tried uninstalling ps4-waker and cmdswitch2, and also reinstall playactor, to start from the beginning. When i log into playactor, it seems my credentials are still saved as im not asked to log again on my playstation account, it log automatically the first time.
I managed to add PS4 and PS5 into apple Home app but they don't work both at the same time : when PS4 is connected , the PS5 disappeared from homebridge accessory, and appear with "no answer" in apple home, and when the PS5 appears in homebridge, the PS4 disappeared, with the same "no answer" in apple Home app. 
Is there a way to configure the plugin so both the playstation stays in homebridge accessories?

**Comment by mesoblaste** [comment]
In addition, i noticed that each time i restart homebridge, when the playstation plugin start, it add my PS4 into accessories in homebridge, running on a different (apparently random) port at each restart, and it also wake the playstation... Is there a way to avoir that?

here is what i got in the log when i wake the PS4 : 

> [09/02/2022, 17:37:02] [playstation] Adding new accessory: PS4-XXX
> [09/02/2022, 17:37:02] PS4-085 4DCC is running on port 37455.
> [09/02/2022, 17:37:02] Please add [PS4-XXX XXXX] manually in Home app. Setup Code: XXX-XX-XXX

**Comment by grelca** [comment]
i also have both a PS4 and PS5 running in my house, so i created a PR to support this :)
https://github.com/kopiro/homebridge-playstation/pull/22

**Comment by mesoblaste** [comment]
That s great, thanks.
Does that mean that after approval, plugin would be updated to support this feature right away?
