### ISSUE TITLE
Unable to complete setup on Synology Docker

### ISSUE THREAD

**Issue by ebfg** [kopiro/homebridge-playstation#51]
I was able to successfully complete auth via `homebridge-playstation-login`: 

```
root@hombridge: homebridge-playstation-login
Discovered device: {
  address: { address: '192.168.X.Y', family: 'IPv4', port: 9302, size: 170 },
  hostRequestPort: 997,
  extras: {
    statusLine: '620 Server Standby',
    statusCode: '620',
    statusMessage: 'Server',
    status: 'STANDBY'
  },
  discoveryVersion: '00030010',
  systemVersion: '06020004',
  id: 'ABCDEF',
  name: 'PS5-XYZ',
  status: 'STANDBY',
  type: 'PS5'
}
Authenticate to PS5-XYZ? (y/n) y
Connecting to <ABCDEF>... // PS5 turns on at this point
Connection successful, wait a bit so we can safely close the connection...

Discovering next device...

Please restart Homebridge now!
```

However, I don't see the `"Please add [PS5 XYZ] manually in Home app. Setup Code: 111-22-333"` message post-reboot.

In the logs post-reboot:

```
root@homebridge:/var/lib/homebridge $ grep -i playstation /var/lib/homebridge/homebridge.log 
[10/22/2022, 4:58:10 PM] Loaded plugin: homebridge-playstation@1.4.2
[10/22/2022, 4:58:10 PM] Registering platform 'homebridge-playstation.playstation'
root@homebridge:/var/lib/homebridge $ grep -i ps5 /var/lib/homebridge/homebridge.log
root@homebridge:/var/lib/homebridge $ 
```

Homebridge version: 1.5.0
Plugin version: 1.4.2
DSM: 6

**Comment by pepegragera** [comment]
Hi, I've had the same problem, the solution is to remove the bridges and accessories from the homebrige settings, despite uninstalling the plugin several times this always remained active, once you remove it it will reappear in your homekit

**Comment by kopiro** [comment]
Hello; try to remove the PS5 accessory in Homebridge from Settings > Unpair Bridges / Cameras / TVs / External Accessories ; to also reset credentials remove Playactor configuration manually by removing the directory `/home/homebridge/.config/playactor`
