### ISSUE TITLE
Unable to request credentials error

### ISSUE THREAD

**Issue by GaintPumpkinz** [kopiro/homebridge-playstation#55]
it shows the status of my ps5 being on or off but whenever i try to use homekit to turn it on or off it just says "Unable to request credentials"

I am very new to this and have no clue whats wrong but if I had to guess its something with playactor I don't have terminal access on homebridge on windows and I'm not sure I installed it in the correct place

**Comment by pepegragera** [comment]
Some problem

**Comment by sterumbelow** [comment]
Same here. It stems from the credentials never being accepted. At the point you enter the code provided on the PS5, it doesn't like it. It gives an EAccess error which I and many others have had. No idea how to fix it!

**Comment by sterumbelow** [comment]
Finally fixed mine! Check this thread:

https://github.com/kopiro/homebridge-playstation/issues/24

**Comment by kopiro** [comment]
Yes, this looks like a UNIX permission error; make sure that the user you use for homebridge (usually called `homebridge`) can read/write the directory `/home/homebridge/.config/playactor`
