### ISSUE TITLE
[Registration error: 403: Forbidden: Invalid PSN ID]

### ISSUE THREAD

**Issue by csoprano** [kopiro/homebridge-playstation#58]
Hi all,

I have followed all the steps in the guide, when I enter the link code displayed on the ps5 I get this error:

[Registration error: 403: Forbidden: Invalid PSN ID]

does anyone know how to fix?
thank you

**Comment by kopiro** [comment]
Hello; it looks like something for the library we use - please try to open an issue on their side: https://github.com/dhleong/playactor/issues
