### ISSUE TITLE
How do I reset the set up for the PS5/How do I remove and re-add the PS5 following all the steps again?

### ISSUE THREAD

**Issue by myaseena786** [kopiro/homebridge-playstation#62]
**Describe Your Problem:**
I have followed all the steps but it tells me that my credentials are a problem. I would like to remove all my credentials if that is possible to start again from scratch. Everytime i remove the plugin and add it again, all my PS credentials are already added in.
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by beslergr** [comment]
Wondering the same ... had to do a fresh HomeBridge install and PS5 won't turn off with the plugin, which I'm assuming is due to this.

**Comment by kopiro** [comment]
Hello; remove the PS5 accessory in Homebridge from Settings > Unpair Bridges / Cameras / TVs / External Accessories ; to also reset credentials remove Playactor configuration manually by removing the directory `/home/homebridge/.config/playactor`
