### ISSUE TITLE
Can't add the PS5 as accessory to HomeKit, as it is not found

### ISSUE THREAD

**Issue by sven2105** [kopiro/homebridge-playstation#66]
**Describe Your Problem:**
I added the ps5 to my homebridge and it works fine i himebridge.
Sadly I can't add the PS5 in HomeKit, as it isn't found
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
{
    "pollInterval": 5000,
    "platform": "playstation"
}
```

**Screenshots:**
![1](https://user-images.githubusercontent.com/114193337/229348102-b9dadc79-38c9-4e8c-be04-ab14ad3e6cc6.jpg)

**Environment:**

* **Plugin Version**: v1.4.2
* **Homebridge Version**: V1.6.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Raspbian GNU/Linux 11 (bullseye)

**Comment by kopiro** [comment]
Hello; try to remove the PS5 accessory in Homebridge from Settings > Unpair Bridges / Cameras / TVs / External Accessories ; to also reset credentials remove Playactor configuration manually by removing the directory `/home/homebridge/.config/playactor`

**Comment by sven2105** [comment]
Hi,

the suggested method does not work, as can be seen below

pi@homebridge:/var/lib/homebridge $ rm -r /home/homebridge/.config/playactor
rm: cannot remove '/home/homebridge/.config/playactor': No such file or directory

**Comment by kopiro** [comment]
Hello @sven2105 , are you running `homebridge-playstation-login` as `homebridge` user?

**Comment by sven2105** [comment]
Hi @kopiro 
I am running it as pi users, as j don't have access as a Homebridge user, as I don't know the password

**Comment by sven2105** [comment]
@kopiro what I can see is that the ps5 is available in Homebridge UI yet I cannot see it in Apple home

**Comment by kopiro** [comment]
Have you added the ps5 manually as explained in the guide?

**Comment by sven2105** [comment]
@kopiro the setup code is the acact same one as the one my homebridge in general has. Therefore if I enter it nothing happens.

**Comment by sven2105** [comment]
@kopiro I have figured out why it wasn't working. 
The root cause is, that I have tried it a couple of times and homebridge still had the information of the old accessories, which is why i couldn't add it to apple home.

Here is how i managed to get everything running again.

1.) Unistall plugin using Homebridge UI
2.) rm -r /home/pi/.config/playactor //Note: Pi is my user on this homebridge
3.) delete old accessorie PS5, to do so you need to 
   1.) In the homebridge UI go to the setting button on the top right corner
   2.) open "Homebridge settings"
   3.) open "Unpair Bridges / Cameras / TVs / External Accessories"
   4.) remove all instances of the PS5
4.) restart homebridge and follow your instructions again :)

**Comment by kopiro** [comment]
Yes, I said in the beginning "try to remove the PS5 accessory in Homebridge from Settings > Unpair Bridges / Cameras / TVs / External Accessories" :)

Glad you solved it though!

**Comment by sven2105** [comment]
@kopiro I misread it and thought I should remove it in apple home under bridges :)
