### ISSUE TITLE
PS5 turns on when restarting HB

### ISSUE THREAD

**Issue by adamrzanek** [kopiro/homebridge-playstation#7]
My PlayStation is turning on when i’m restarting Homebridge. Then it’s becoming „no response” in homekit until i fully login to psn.

**Comment by kopiro** [comment]
Hello; I actually got woken up tonight by this bug - I solved it in version 1.2.0 (https://github.com/kopiro/homebridge-playstation/releases/tag/v1.2.0)

Please update, and thanks for reporting.
