### ISSUE TITLE
When PS5 is not available update status to "Off"

### ISSUE THREAD

**Issue by sven2105** [kopiro/homebridge-playstation#70]
**Is your feature request related to a problem? Please describe:**

When the PS5 is turned off completely, the status of the accessorie isn't updated. Therefore in the homebridge UI as well as in the apple home app the PS5 is still active.,which is not the current status.

**Describe the solution you'd like:**
After 5 retries to connect to the ps5 I would like the button to be switched off. This indicates that something is wrong and the status is rightfully "inactive"

**Additional context:**
If  ([playstation] Unable to locate device)
{PS5-xyz == inactive;]

**Comment by sven2105** [comment]
Hi @kopiro 
Would you be so kind and check me request ?
It would really help me when the button would be turned off when the pa5 is not reachable.
Would that be possible?

**Comment by kopiro** [comment]
I can try to look into today :)

**Comment by sven2105** [comment]
Hi @kopiro 

Did you have the time to look into this topic ?

**Comment by kopiro** [comment]
Hello @sven2105 , I'm sorry I have been in vacation for a while now and didn't have time to play with the PS5.
Hopefully this week I can do smth.

**Comment by sven2105** [comment]
Hi @kopiro 
Hope you had wonderful holidays.
Did you have the time to look into my request ?

**Comment by J7mbo** [comment]
Hey folks - do I understand correctly that the button in HomeKit always shows the PS5 as "on", even when it's NOT on???? Is that really the case?

**Comment by sven2105** [comment]
Hi @J7mbo yes this is the case
If the ps5 is "off" it is shown as active in HomeKit
If the PS5 is in "stands/rest" it is shown as inactive.

**Comment by bollee23** [comment]
Hi, I support this this feature request ;-), would be cool when available as I started to completely switch off my PS4/PS5

**Comment by kopiro** [comment]
Hey, this should be fixed in 1.5.2
