### ISSUE TITLE
Error Unable to request credentials

### ISSUE THREAD

**Issue by Themaster312** [kopiro/homebridge-playstation#74]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: 

Is there a solution to the problem?

**Comment by dpamping** [comment]
Same issue here
