### ISSUE TITLE
Display device in HomeKit as switch

### ISSUE THREAD

**Issue by njuart** [kopiro/homebridge-playstation#78]
Hi, is there a possibility to display PS5 as regular switch but not as TV accessory? The problem is that when it’s TV accessory it is shown in remote app, but has no practical usage as it’s not working as remote. Thx in advance!

**Comment by J7mbo** [comment]
If it's not super difficult we can do it ourselves, it should be a one-liner somewhere in the code right?

**Comment by seifscape** [comment]
You need to modify this line of code: 
https://github.com/kopiro/homebridge-playstation/blob/609ee021e849bd6ee88469145a2d5a89a2f2f1ff/src/playstationAccessory.ts#L44

    this.accessory.category = this.api.hap.Categories.TV_SET_TOP_BOX; to
        this.accessory.category = this.api.hap.Categories.SWITCH;
