### ISSUE TITLE
Start titles

### ISSUE THREAD

**Issue by MozkaGit** [kopiro/homebridge-playstation#79]
Hello, do you know if it is possible to start games with this plugin ? In the PR's I see that @robi-van-kenobi [integrated this feature](https://github.com/kopiro/homebridge-playstation/pull/75) several months ago but @kopiro didn't made the merge yet. Has anyone tried to manually modify the plugin to try to get this feature to work? If it's possible, how can I proceed please?

**Comment by robi-van-kenobi** [comment]
Hi @MozkaGit , I have my version running locally. It works pretty well.

@kopiro bump.

**Comment by kopiro** [comment]
https://github.com/kopiro/homebridge-playstation/releases/tag/v1.5.0
