### ISSUE TITLE
Titles doesn't start

### ISSUE THREAD

**Issue by MozkaGit** [kopiro/homebridge-playstation#81]
Hello @robi-van-kenobi I have trouble with your implementation #75. Can you explain how it works ?

I added few games in my config (I got IDs from ps store website) :

```
{
    "pollInterval": 5000,
    "apps": [
        {
            "id": "CUSA11513_00",
            "name": "Phoenix Wright"
        },
        {
            "id": "PPSA08330_00",
            "name": "GOW Ragnarok"
        },
        {
            "id": "PPSA04029_00",
            "name": "Cyberpunk"
        }
    ],
    "platform": "playstation"
}
```
it gives me this on home app :

![IMG_0146](https://github.com/kopiro/homebridge-playstation/assets/43102748/2a9b7bc7-ec54-4289-9dfa-4fb9f060680f)

I have to start the PS5 before selecting any titles but when I do this the titles are not starting. Am I proceeding in the right way?

**Comment by beliy82** [comment]
same here

**Comment by kopiro** [comment]
AFAIK this implementation doesn't work with PS5, only PS4
