### ISSUE TITLE
Update v.1.5.2. Bug

### ISSUE THREAD

**Issue by Stewart06** [kopiro/homebridge-playstation#87]
Bonjour,

Depuis que j'ai fait la dernière mise a jour, mais deux plantation 5 sont passées hors-ligne.
J'ai tout réinitialiser et maintenant impossible d'ajouter les deux consoles.

Good morning,

Since I did the last update, but two plantation 5s have gone offline.
I reset everything and now unable to add the two consoles.

**Comment by Aransh** [comment]
Possibly same problem as me https://github.com/kopiro/homebridge-playstation/issues/86

**Comment by Stewart06** [comment]
Moi je n'ai même pas modifié le nom, j'ai juste fait la mise à jour !

I didn't even change the name, I just updated it!

**Comment by kopiro** [comment]
Hello, this issue has been solved in https://github.com/kopiro/homebridge-playstation/releases/tag/v1.6.0
