### ISSUE TITLE
Multiple Devices PS4 & PS5, only 1 is responding.

### ISSUE THREAD

**Issue by GiovanniDw** [kopiro/homebridge-playstation#89]
**Describe The Bug:**

PS4 & PS5 Not showing up simultaneously since last update.

**To Reproduce:**

Update to latest version I think.

**Expected behavior:**

To have a PS4 & PS5 simultaneously.
**Logs:**

```zsh
[11/15/2023, 3:40:33 PM] [homebridge-playstation] Unable to locate device: with id 00D9D13F3EFF
Error: from server 192.168.1.99:54586 Error: connect ECONNREFUSED 192.168.1.99:54586
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.99',
  port: 54586
}
```

**Plugin Config:**

```json
{
            "pollInterval": 10000,
            "_bridge": {
                "username": "0E:1A:0D:EA:5A:79",
                "port": 44176
            },
            "platform": "playstation"
},
```

**Screenshots:**

Plugin Version: 1.5.1
<img width="701" alt="Screenshot 2023-11-15 at 15 39 06" src="https://github.com/kopiro/homebridge-playstation/assets/10939082/62e98b25-5647-41d7-b53f-5436d1a27dcb">

Plugin Version: 1.5.0 (After Downgrading)
<img width="701" alt="image" src="https://github.com/kopiro/homebridge-playstation/assets/10939082/84740a04-350b-4869-8426-f44556b7dca7">

**Environment:**

* **Plugin Version**: 1.5.1
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 20.9.0
* **NPM Version**: 10.2.3
* **Operating System**: MacOS 12.7.1

**Comment by kopiro** [comment]
Hello, this issue has been solved in https://github.com/kopiro/homebridge-playstation/releases/tag/v1.6.0
