### ISSUE TITLE
Incomplete setup - "Choose how you would like this set-top box to work in your home"

### ISSUE THREAD

**Issue by MoienTajik** [kopiro/homebridge-playstation#93]
**Describe The Bug:**
While setting up the device in HomeKit, there's a step with the message "Choose how you would like this set-top box to work in your home" and then you have to choose "Input Source". The problem is that there's no Input Sources to select in this step and this causes broken setup.

**To Reproduce:**
Try to add device based on README in HomeKit.

**Expected behavior:**
Either having the Input Sources to choose or not asking for that at all (maybe have to change accessory type to Switch in order to skip that).

**Plugin Config:**

```json
{
    "pollInterval": 5000,
    "overrides": [
        {
            "deviceId": "C84AA0733AU2",
            "name": "PS5"
        }
    ],
    "platform": "playstation"
}
```

**Screenshots:**
<img src="https://github.com/kopiro/homebridge-playstation/assets/21059063/8b5b8f13-42c7-4359-ae05-de3ea160b4ac" height="800px" width="370px" />

**Environment:**
* **Plugin Version**: v1.6.0
* **Homebridge Version**:  v1.7.0
* **Operating System**: macOS

**Comment by philthuene** [comment]
Havinf the same issue here on my end. When trying to continue, this message shows: 
![IMG_EF390B1FCA14-1](https://github.com/kopiro/homebridge-playstation/assets/68222777/7de78733-1ddb-4763-b94c-f1d97ede0956)

**Comment by Jelledb** [comment]
Running into the same issue. However, it does seem to work when you close the wizard at that point and click "Save and Finish Later"

I think what others mentioned elsewhere is that it might be better to let the PlayStation show up as a switch.

**Comment by muenzpraeger** [comment]
The dialog is a textfield (not well visible). You can just tap into it, and set a random string. With that the setup can be finished.

**Comment by MoienTajik** [comment]
Fixed based on @muenzpraeger's comment.
