### ISSUE TITLE
PS5 input keeps defaulting to '---' when on?

### ISSUE THREAD

**Issue by t6mbrown** [kopiro/homebridge-playstation#96]
**Describe The Bug:**
 When I turn the PS5 on it doesn't say 'On', it says '---'. I can change the input in the settings to 'On' but it then changes back after about a minute?

**To Reproduce:**
 Turn on PS5.

**Expected behavior:**
 To state 'On'.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
{
    "pollInterval": 5000,
    "platform": "playstation"
}
```

**Screenshots:**
 <img width="161" alt="Screenshot 2024-01-17 at 23 44 37" src="https://github.com/kopiro/homebridge-playstation/assets/156970491/adb6d53d-e20b-4621-9848-86324c6a9728">
<img width="901" alt="Screenshot 2024-01-17 at 23 44 56" src="https://github.com/kopiro/homebridge-playstation/assets/156970491/b40b46a9-cfe1-489f-a616-7e50bcea41e2">

**Environment:**

* **Plugin Version**: v1.6.0
* **Homebridge Version**:  v1.7.0
* **Node.js Version**:  v20.10.0
* **NPM Version**: ?
* **Operating System**:  macOS

**Comment by kopiro** [comment]
Yes; this is because on PS4 you should be able to see the title currently running in there.
We hope to support this feature in Ps5 but no update yet.

**Comment by jbbmb** [comment]
@kopiro but can we change the default to “On” instead of “---“? It makes more sense, since it will show On/Off for PS5 and game titles when a PS4 is On.

**Comment by kopiro** [comment]
Okay, I can do it; I can make it an option

**Comment by Rabbit-Spec** [comment]
> Okay, I can do it; I can make it an option

No update yet?

**Comment by deeeemiss** [comment]
Still nothing? Also, why PS5 doesn't support this feature and PS4 yes? (Just out of curiosity, even in few words)

**Comment by t6mbrown** [comment]
Hi @kopiro, any update regarding this yet? :)
